/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestMetaOauthRouteImport } from './routes/test-meta-oauth'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RetentioRouteImport } from './routes/retentio'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestaoObrigadoRouteImport } from './routes/gestao-obrigado'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestMetaOauthCallbackRouteImport } from './routes/test-meta-oauth.callback'
import { Route as PPortalSlugRouteImport } from './routes/p.$portalSlug'
import { Route as DiagnosticoDiagnosisIdRouteImport } from './routes/diagnostico.$diagnosisId'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedStandupRouteImport } from './routes/_authenticated/standup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlatformAdminRouteImport } from './routes/_authenticated/platform-admin'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreativesRouteImport } from './routes/_authenticated/creatives'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAiReviewRouteImport } from './routes/_authenticated/ai-review'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as DiagnosticoDiagnosisIdConectarRouteImport } from './routes/diagnostico.$diagnosisId.conectar'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as AuthenticatedIntegrationsOauthCallbackRouteImport } from './routes/_authenticated/integrations.oauth.callback'

const TestMetaOauthRoute = TestMetaOauthRouteImport.update({
  id: '/test-meta-oauth',
  path: '/test-meta-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentioRoute = RetentioRouteImport.update({
  id: '/retentio',
  path: '/retentio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoObrigadoRoute = GestaoObrigadoRouteImport.update({
  id: '/gestao-obrigado',
  path: '/gestao-obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestMetaOauthCallbackRoute = TestMetaOauthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => TestMetaOauthRoute,
} as any)
const PPortalSlugRoute = PPortalSlugRouteImport.update({
  id: '/p/$portalSlug',
  path: '/p/$portalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoDiagnosisIdRoute = DiagnosticoDiagnosisIdRouteImport.update({
  id: '/diagnostico/$diagnosisId',
  path: '/diagnostico/$diagnosisId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStandupRoute = AuthenticatedStandupRouteImport.update({
  id: '/standup',
  path: '/standup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlatformAdminRoute =
  AuthenticatedPlatformAdminRouteImport.update({
    id: '/platform-admin',
    path: '/platform-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreativesRoute = AuthenticatedCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiReviewRoute = AuthenticatedAiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DiagnosticoDiagnosisIdConectarRoute =
  DiagnosticoDiagnosisIdConectarRouteImport.update({
    id: '/conectar',
    path: '/conectar',
    getParentRoute: () => DiagnosticoDiagnosisIdRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsOauthCallbackRoute =
  AuthenticatedIntegrationsOauthCallbackRouteImport.update({
    id: '/oauth/callback',
    path: '/oauth/callback',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gestao-obrigado': typeof GestaoObrigadoRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retentio': typeof RetentioRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/test-meta-oauth': typeof TestMetaOauthRouteWithChildren
  '/actions': typeof AuthenticatedActionsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/creatives': typeof AuthenticatedCreativesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standup': typeof AuthenticatedStandupRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$diagnosisId': typeof DiagnosticoDiagnosisIdRouteWithChildren
  '/p/$portalSlug': typeof PPortalSlugRoute
  '/test-meta-oauth/callback': typeof TestMetaOauthCallbackRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/diagnostico/$diagnosisId/conectar': typeof DiagnosticoDiagnosisIdConectarRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/integrations/oauth/callback': typeof AuthenticatedIntegrationsOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gestao-obrigado': typeof GestaoObrigadoRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retentio': typeof RetentioRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/test-meta-oauth': typeof TestMetaOauthRouteWithChildren
  '/actions': typeof AuthenticatedActionsRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ai-review': typeof AuthenticatedAiReviewRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/creatives': typeof AuthenticatedCreativesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/health': typeof AuthenticatedHealthRoute
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/standup': typeof AuthenticatedStandupRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$diagnosisId': typeof DiagnosticoDiagnosisIdRouteWithChildren
  '/p/$portalSlug': typeof PPortalSlugRoute
  '/test-meta-oauth/callback': typeof TestMetaOauthCallbackRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/diagnostico/$diagnosisId/conectar': typeof DiagnosticoDiagnosisIdConectarRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/integrations/oauth/callback': typeof AuthenticatedIntegrationsOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gestao-obrigado': typeof GestaoObrigadoRoute
  '/login': typeof LoginRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/retentio': typeof RetentioRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/test-meta-oauth': typeof TestMetaOauthRouteWithChildren
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ai-review': typeof AuthenticatedAiReviewRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/creatives': typeof AuthenticatedCreativesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/standup': typeof AuthenticatedStandupRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$diagnosisId': typeof DiagnosticoDiagnosisIdRouteWithChildren
  '/p/$portalSlug': typeof PPortalSlugRoute
  '/test-meta-oauth/callback': typeof TestMetaOauthCallbackRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/diagnostico/$diagnosisId/conectar': typeof DiagnosticoDiagnosisIdConectarRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/integrations/oauth/callback': typeof AuthenticatedIntegrationsOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/demo'
    | '/forgot-password'
    | '/gestao-obrigado'
    | '/login'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/retentio'
    | '/signup'
    | '/termos'
    | '/test-meta-oauth'
    | '/actions'
    | '/activity'
    | '/admin'
    | '/ai-review'
    | '/alerts'
    | '/competitors'
    | '/creatives'
    | '/dashboard'
    | '/health'
    | '/integrations'
    | '/onboarding'
    | '/platform-admin'
    | '/reports'
    | '/settings'
    | '/standup'
    | '/whatsapp'
    | '/diagnostico/$diagnosisId'
    | '/p/$portalSlug'
    | '/test-meta-oauth/callback'
    | '/clients/$clientId'
    | '/diagnostico/$diagnosisId/conectar'
    | '/clients/'
    | '/integrations/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/demo'
    | '/forgot-password'
    | '/gestao-obrigado'
    | '/login'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/retentio'
    | '/signup'
    | '/termos'
    | '/test-meta-oauth'
    | '/actions'
    | '/activity'
    | '/admin'
    | '/ai-review'
    | '/alerts'
    | '/competitors'
    | '/creatives'
    | '/dashboard'
    | '/health'
    | '/integrations'
    | '/onboarding'
    | '/platform-admin'
    | '/reports'
    | '/settings'
    | '/standup'
    | '/whatsapp'
    | '/diagnostico/$diagnosisId'
    | '/p/$portalSlug'
    | '/test-meta-oauth/callback'
    | '/clients/$clientId'
    | '/diagnostico/$diagnosisId/conectar'
    | '/clients'
    | '/integrations/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/demo'
    | '/forgot-password'
    | '/gestao-obrigado'
    | '/login'
    | '/obrigado'
    | '/privacidade'
    | '/reset-password'
    | '/retentio'
    | '/signup'
    | '/termos'
    | '/test-meta-oauth'
    | '/_authenticated/actions'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/ai-review'
    | '/_authenticated/alerts'
    | '/_authenticated/competitors'
    | '/_authenticated/creatives'
    | '/_authenticated/dashboard'
    | '/_authenticated/health'
    | '/_authenticated/integrations'
    | '/_authenticated/onboarding'
    | '/_authenticated/platform-admin'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/standup'
    | '/_authenticated/whatsapp'
    | '/diagnostico/$diagnosisId'
    | '/p/$portalSlug'
    | '/test-meta-oauth/callback'
    | '/_authenticated/clients/$clientId'
    | '/diagnostico/$diagnosisId/conectar'
    | '/_authenticated/clients/'
    | '/_authenticated/integrations/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GestaoObrigadoRoute: typeof GestaoObrigadoRoute
  LoginRoute: typeof LoginRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RetentioRoute: typeof RetentioRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  TestMetaOauthRoute: typeof TestMetaOauthRouteWithChildren
  DiagnosticoDiagnosisIdRoute: typeof DiagnosticoDiagnosisIdRouteWithChildren
  PPortalSlugRoute: typeof PPortalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-meta-oauth': {
      id: '/test-meta-oauth'
      path: '/test-meta-oauth'
      fullPath: '/test-meta-oauth'
      preLoaderRoute: typeof TestMetaOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retentio': {
      id: '/retentio'
      path: '/retentio'
      fullPath: '/retentio'
      preLoaderRoute: typeof RetentioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao-obrigado': {
      id: '/gestao-obrigado'
      path: '/gestao-obrigado'
      fullPath: '/gestao-obrigado'
      preLoaderRoute: typeof GestaoObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-meta-oauth/callback': {
      id: '/test-meta-oauth/callback'
      path: '/callback'
      fullPath: '/test-meta-oauth/callback'
      preLoaderRoute: typeof TestMetaOauthCallbackRouteImport
      parentRoute: typeof TestMetaOauthRoute
    }
    '/p/$portalSlug': {
      id: '/p/$portalSlug'
      path: '/p/$portalSlug'
      fullPath: '/p/$portalSlug'
      preLoaderRoute: typeof PPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/$diagnosisId': {
      id: '/diagnostico/$diagnosisId'
      path: '/diagnostico/$diagnosisId'
      fullPath: '/diagnostico/$diagnosisId'
      preLoaderRoute: typeof DiagnosticoDiagnosisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/standup': {
      id: '/_authenticated/standup'
      path: '/standup'
      fullPath: '/standup'
      preLoaderRoute: typeof AuthenticatedStandupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform-admin': {
      id: '/_authenticated/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/creatives': {
      id: '/_authenticated/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof AuthenticatedCreativesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-review': {
      id: '/_authenticated/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AuthenticatedAiReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/diagnostico/$diagnosisId/conectar': {
      id: '/diagnostico/$diagnosisId/conectar'
      path: '/conectar'
      fullPath: '/diagnostico/$diagnosisId/conectar'
      preLoaderRoute: typeof DiagnosticoDiagnosisIdConectarRouteImport
      parentRoute: typeof DiagnosticoDiagnosisIdRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/oauth/callback': {
      id: '/_authenticated/integrations/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/integrations/oauth/callback'
      preLoaderRoute: typeof AuthenticatedIntegrationsOauthCallbackRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
  }
}

interface AuthenticatedIntegrationsRouteChildren {
  AuthenticatedIntegrationsOauthCallbackRoute: typeof AuthenticatedIntegrationsOauthCallbackRoute
}

const AuthenticatedIntegrationsRouteChildren: AuthenticatedIntegrationsRouteChildren =
  {
    AuthenticatedIntegrationsOauthCallbackRoute:
      AuthenticatedIntegrationsOauthCallbackRoute,
  }

const AuthenticatedIntegrationsRouteWithChildren =
  AuthenticatedIntegrationsRoute._addFileChildren(
    AuthenticatedIntegrationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAiReviewRoute: typeof AuthenticatedAiReviewRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedCreativesRoute: typeof AuthenticatedCreativesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlatformAdminRoute: typeof AuthenticatedPlatformAdminRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStandupRoute: typeof AuthenticatedStandupRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAiReviewRoute: AuthenticatedAiReviewRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedCreativesRoute: AuthenticatedCreativesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlatformAdminRoute: AuthenticatedPlatformAdminRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStandupRoute: AuthenticatedStandupRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TestMetaOauthRouteChildren {
  TestMetaOauthCallbackRoute: typeof TestMetaOauthCallbackRoute
}

const TestMetaOauthRouteChildren: TestMetaOauthRouteChildren = {
  TestMetaOauthCallbackRoute: TestMetaOauthCallbackRoute,
}

const TestMetaOauthRouteWithChildren = TestMetaOauthRoute._addFileChildren(
  TestMetaOauthRouteChildren,
)

interface DiagnosticoDiagnosisIdRouteChildren {
  DiagnosticoDiagnosisIdConectarRoute: typeof DiagnosticoDiagnosisIdConectarRoute
}

const DiagnosticoDiagnosisIdRouteChildren: DiagnosticoDiagnosisIdRouteChildren =
  {
    DiagnosticoDiagnosisIdConectarRoute: DiagnosticoDiagnosisIdConectarRoute,
  }

const DiagnosticoDiagnosisIdRouteWithChildren =
  DiagnosticoDiagnosisIdRoute._addFileChildren(
    DiagnosticoDiagnosisIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GestaoObrigadoRoute: GestaoObrigadoRoute,
  LoginRoute: LoginRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RetentioRoute: RetentioRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  TestMetaOauthRoute: TestMetaOauthRouteWithChildren,
  DiagnosticoDiagnosisIdRoute: DiagnosticoDiagnosisIdRouteWithChildren,
  PPortalSlugRoute: PPortalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
